export const LIST_LAUNCHES = 'LIST_LAUNCHES';
export const SUCCESS_LAUNCHES = 'SUCCESS_LAUNCHES';
export const FAILED_LAUNCHES = 'FAILED_LAUNCHES';
export const UPCOMING_LAUNCHES = 'UPCOMING_LAUNCHES';
export const GET_LAUNCH = 'GET_LAUNCH';